pod 'HyphenateFullSDK', :git => 'https://github.com/easemob/hyphenate-full-cocoapods.git'
pod 'AFNetworking', '~> 3.0.4'
pod 'SVProgressHUD', '~> 2.0-beta8'
pod 'SSKeychain', '~> 1.4.0'
pod 'MJRefresh', '~> 3.1.0'
pod 'Masonry', '~> 0.6.4'
pod 'Wonderful', '~> 1.2.0'
